language: python
python: 3.4
env:
    - TOX_ENV=py26
    - TOX_ENV=py26-odict
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
install:
    - pip install tox setuptools==7.0
script:
    - tox -e $TOX_ENV

